name: uts
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  shared_preferences: ^2.2.2
  twilio_flutter: ^0.0.9
  image_picker: ^1.1.1
  file_picker: ^5.0.0
  flutter_sound: ^9.0.3
  permission_handler: ^11.1.0
  path: ^1.8.2
  flutter_webrtc: ^0.10.0
  phone_state: ^1.0.4
  camera: ^0.10.0
  table_calendar: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
